docs/AboutUs.md
=> Add Audi's details

docs/AboutUs.md
Closes #46
Add my information to AboutUs.md.
Additionally, I have edited @zzawook's details to split into Roles and Responsibilities
=> docs: Add Dave's information to AboutUs.md

docs/DeveloperGuide.md
=> Add user stories to DeveloperGuide.md

docs/DeveloperGuide.md
=> Update nfr and glossary

docs/DeveloperGuide.md
=> Edit Target User Profile and Value Proposition

src/main/java/keycontacts/model/pianopiece/PianoPiece.java, src/test/java/keycontacts/model/pianopiece/PianoPieceTest.java
Replicates the implementation of tag model and testing. Closes #81
=> Implement PianoPiece model and testing

src/main/java/keycontacts/logic/commands/CancelLessonCommand.java, src/main/java/keycontacts/logic/parser/CancelLessonCommandParser.java, src/main/java/keycontacts/logic/parser/CliSyntax.java, src/main/java/keycontacts/logic/parser/KeyContactsParser.java, src/main/java/keycontacts/logic/parser/ParserUtil.java
=> Add CancelLessonCommand and it's parser

src/main/java/keycontacts/logic/Messages.java, src/main/java/keycontacts/logic/commands/AssignPiecesCommand.java, src/main/java/keycontacts/logic/commands/ScheduleCommand.java, src/main/java/keycontacts/logic/parser/AssignPiecesCommandParser.java, src/main/java/keycontacts/logic/parser/CliSyntax.java, src/main/java/keycontacts/logic/parser/KeyContactsParser.java, src/main/java/keycontacts/logic/parser/ParserUtil.java, src/main/java/keycontacts/model/pianopiece/PianoPiece.java, src/main/java/keycontacts/model/student/Student.java, src/main/java/keycontacts/model/util/SampleDataUtil.java, src/main/java/keycontacts/storage/JsonAdaptedPianoPiece.java, src/main/java/keycontacts/storage/JsonAdaptedStudent.java, src/main/java/keycontacts/ui/StudentCard.java, src/main/resources/view/StudentListCard.fxml, src/test/data/JsonSerializableStudentDirectoryTest/typicalStudentsStudentDirectory.json, src/test/java/keycontacts/logic/commands/AssignPiecesCommandTest.java, src/test/java/keycontacts/logic/commands/CommandTestUtil.java, src/test/java/keycontacts/logic/commands/EditCommandTest.java, src/test/java/keycontacts/logic/parser/AssignPiecesCommandParserTest.java, src/test/java/keycontacts/logic/parser/KeyContactsParserTest.java, src/test/java/keycontacts/model/pianopiece/PianoPieceTest.java, src/test/java/keycontacts/model/student/StudentTest.java, src/test/java/keycontacts/storage/JsonAdaptedPianoPieceTest.java, src/test/java/keycontacts/storage/JsonAdaptedStudentTest.java, src/test/java/keycontacts/testutil/StudentBuilder.java, src/test/java/keycontacts/testutil/TypicalStudents.java
Add the AssignPianoPiece command, which assigns one or more piano pieces to the student identified by the provided index.
Closes #82
=> Add AssignPianoPiece command

src/main/java/keycontacts/model/lesson/MakeupLesson.java
Fixes https://github.com/AY2425S1-CS2103T-T08-2/tp/issues/88
=> Create class for MakeupLesson

docs/DeveloperGuide.md, docs/UserGuide.md
=> Add documentation for assign command

src/main/java/keycontacts/model/pianopiece/PianoPiece.java, src/main/java/keycontacts/model/util/SampleDataUtil.java, src/main/resources/view/DarkTheme.css, src/test/java/keycontacts/logic/commands/AssignPiecesCommandTest.java, src/test/java/keycontacts/logic/commands/CommandTestUtil.java, src/test/java/keycontacts/logic/parser/AssignPiecesCommandParserTest.java, src/test/java/keycontacts/logic/parser/KeyContactsParserTest.java, src/test/java/keycontacts/model/student/StudentTest.java, src/test/java/keycontacts/testutil/StudentBuilder.java
=> Refactor getPianoPieces method

src/test/java/keycontacts/logic/commands/AssignPiecesCommandTest.java
=> Refactor test to use assertCommand assertions

src/main/java/keycontacts/model/lesson/Day.java, src/test/java/keycontacts/logic/commands/ScheduleCommandTest.java, src/test/java/keycontacts/logic/parser/KeyContactsParserTest.java, src/test/java/keycontacts/model/lesson/RegularLessonTest.java, src/test/java/keycontacts/testutil/RegularLessonBuilder.java
Small refactoring of some schedule/lesson tests
=> refactor: Refactor schedule tests

docs/UserGuide.md, src/main/java/keycontacts/MainApp.java, src/main/java/keycontacts/logic/Messages.java, src/main/java/keycontacts/logic/commands/CancelLessonCommand.java, src/main/java/keycontacts/logic/commands/MakeupLessonCommand.java, src/main/java/keycontacts/logic/commands/ScheduleCommand.java, src/main/java/keycontacts/model/lesson/Date.java, src/main/java/keycontacts/model/lesson/MakeupLesson.java, src/main/java/keycontacts/model/student/GradeLevel.java, src/main/java/keycontacts/model/student/Student.java, src/main/java/keycontacts/model/util/SampleDataUtil.java, src/main/java/keycontacts/ui/StudentCard.java, src/main/resources/view/StudentListCard.fxml, src/test/data/JsonSerializableStudentDirectoryTest/duplicateStudentStudentDirectory.json, src/test/data/JsonSerializableStudentDirectoryTest/invalidStudentStudentDirectory.json, src/test/data/JsonStudentDirectoryStorageTest/invalidAndValidStudentStudentDirectory.json, src/test/data/JsonStudentDirectoryStorageTest/invalidStudentStudentDirectory.json, src/test/java/keycontacts/logic/commands/CancelLessonCommandTest.java, src/test/java/keycontacts/logic/commands/ScheduleCommandTest.java
Closes #114 
Additionally, this introduces several cosmetic changes to ensure the repo is ready for release
- Bumps the version in `MainApp`
- Refactors `Student` with a private inner class `Updater`, for greater extensibility
- Formatting date for display has been shifted into `Date`
- More detailed success message for `MakeupLessonCommand`
- Minor improvements to UI of `StudentCard`
- Better sample data in `SampleDataUtil` (in general let's keep all dates used in testing to dates in 2024)
- Reordered 1 section of UserGuide
=> chore: Clean up code base for release

build.gradle, src/main/java/keycontacts/Main.java
=> build: Enable assertions in build.gradle

docs/UserGuide.md, src/main/java/keycontacts/logic/Logic.java, src/main/java/keycontacts/logic/LogicManager.java, src/main/java/keycontacts/logic/commands/CommandResult.java, src/main/java/keycontacts/logic/commands/ExitCommand.java, src/main/java/keycontacts/logic/commands/HelpCommand.java, src/main/java/keycontacts/logic/commands/ViewCommand.java, src/main/java/keycontacts/logic/parser/KeyContactsParser.java, src/main/java/keycontacts/logic/parser/ViewCommandParser.java, src/main/java/keycontacts/model/Model.java, src/main/java/keycontacts/model/ModelManager.java, src/main/java/keycontacts/model/lesson/Date.java, src/main/java/keycontacts/model/lesson/RegularLesson.java, src/main/java/keycontacts/ui/CalendarView.java, src/main/java/keycontacts/ui/MainWindow.java, src/test/java/keycontacts/logic/LogicManagerTest.java, src/test/java/keycontacts/logic/commands/AddCommandTest.java, src/test/java/keycontacts/logic/commands/CommandResultTest.java, src/test/java/keycontacts/logic/commands/CommandTestUtil.java, src/test/java/keycontacts/logic/commands/ExitCommandTest.java, src/test/java/keycontacts/logic/commands/HelpCommandTest.java, src/test/java/keycontacts/logic/commands/ViewCommandTest.java, src/test/java/keycontacts/logic/parser/KeyContactsParserTest.java, src/test/java/keycontacts/logic/parser/ViewCommandParserTest.java, src/test/java/keycontacts/model/ModelManagerTest.java, src/test/java/keycontacts/model/lesson/DateTest.java, src/test/java/keycontacts/model/lesson/RegularLessonTest.java
=> feat: Link model to calendar view

docs/UserGuide.md, src/main/java/keycontacts/logic/commands/EditCommand.java, src/main/java/keycontacts/logic/commands/FindCommand.java, src/main/java/keycontacts/logic/commands/SortCommand.java, src/main/java/keycontacts/logic/parser/FindCommandParser.java, src/main/java/keycontacts/logic/parser/SortCommandParser.java, src/main/java/keycontacts/model/StudentDirectory.java, src/main/java/keycontacts/model/student/Group.java, src/main/java/keycontacts/model/student/StudentComparator.java, src/main/java/keycontacts/storage/JsonSerializableStudentDirectory.java, src/test/data/JsonSerializableStudentDirectoryTest/GroupSyncErrorStudentDirectoryTest/cancelledLessonsSyncErrorStudentDirectory.json, src/test/data/JsonSerializableStudentDirectoryTest/GroupSyncErrorStudentDirectoryTest/makeupLessonsSyncErrorStudentDirectory.json, src/test/data/JsonSerializableStudentDirectoryTest/GroupSyncErrorStudentDirectoryTest/regularLessonSyncErrorStudentDirectory.json, src/test/java/keycontacts/logic/commands/FindStudentDescriptorTest.java, src/test/java/keycontacts/logic/commands/GroupSyncTest.java, src/test/java/keycontacts/logic/parser/FindCommandParserTest.java, src/test/java/keycontacts/logic/parser/SortCommandParserTest.java, src/test/java/keycontacts/model/student/GroupTest.java, src/test/java/keycontacts/model/student/StudentComparatorTest.java, src/test/java/keycontacts/model/student/StudentDescriptorMatchesPredicateTest.java, src/test/java/keycontacts/storage/JsonSerializableStudentDirectoryTest.java, src/test/java/keycontacts/testutil/FindStudentDescriptorBuilder.java, src/test/java/keycontacts/testutil/TypicalStudents.java
Closes #135 by adding group field to both find and sort command.
Closes #136 by adding documentation in the UG for relevant commands.
Also improves test coverage of group feature.
=> feat: Enhance group feature

docs/diagrams/UiClassDiagram.puml
=> Update UI UML Diagram

docs/diagrams/ArchitectureSequenceDiagram.puml, docs/diagrams/DeleteSequenceDiagram.puml
Updates user guide UML diagrams, specifically the
Architecture Sequence Diagram, and Logic Sequence Diagram
The overall architecture is identical, and so do the logic so there are not much in the diagrams itself, but the commit mostly focuses on the class name changes.
=> Update user guide UML diagrams

docs/diagrams/ModelClassDiagram.puml
=> Add missing fields to Student class in Model UML diagram

docs/diagrams/DeleteSequenceDiagram.puml
=> Fix KeyContactsParser typo in DeleteSequenceDiagram

docs/UserGuide.md, src/main/java/keycontacts/logic/commands/EditCommand.java, src/main/java/keycontacts/logic/commands/MakeupLessonCommand.java, src/main/java/keycontacts/ui/CalendarView.java
Fixes several alpha bugs.
Closes #155 
Closes #145 
Closes #152 
new colour palette ^
=> fix: Fixes alpha bugs

src/main/java/keycontacts/logic/commands/UncancelLessonCommand.java, src/main/java/keycontacts/logic/parser/ArgumentMultimap.java, src/main/java/keycontacts/logic/parser/KeyContactsParser.java, src/main/java/keycontacts/logic/parser/UncancelLessonCommandParser.java, src/main/java/keycontacts/model/student/Student.java, src/main/java/keycontacts/ui/CalendarView.java, src/test/java/keycontacts/logic/commands/UncancelLessonCommandTest.java, src/test/java/keycontacts/logic/parser/KeyContactsParserTest.java, src/test/java/keycontacts/logic/parser/UncancelLessonCommandParserTest.java
=> feat: Implement uncancel command

src/main/java/keycontacts/model/student/GradeLevel.java, src/test/java/keycontacts/model/student/GradeLevelTest.java, src/test/java/keycontacts/storage/JsonAdaptedStudentTest.java
Changes grade level validation to accept any non-empty string with only alphanumeric characters or white spaces
Closes #151 
Closes #149
=> refactor: Refactor GradeLevel class

docs/DeveloperGuide.md
=> docs: Add effort to DG

docs/DeveloperGuide.md
=> Add Manual testing section to the DG

src/main/java/keycontacts/model/student/Group.java, src/main/java/keycontacts/model/student/Student.java, src/test/java/keycontacts/model/student/GroupTest.java, src/test/java/keycontacts/model/student/StudentTest.java
=> refactor: Refactor detection of same group and student

docs/UserGuide.md, docs/_markbind/layouts/default.md
=> Add user guide enhancements

src/main/java/keycontacts/logic/commands/CancelLessonCommand.java
=> Fix cancel not committing directory when canceling makeup lesson

src/main/java/keycontacts/logic/commands/MakeupLessonCommand.java, src/main/java/keycontacts/logic/commands/ScheduleCommand.java
Closes #204 
Closes #234 
Closes #216
=>  Fix identical lessons causing no clash errors

docs/DeveloperGuide.md
Closes #233 
Closes #231
Closes #230 
Closes #228 
Closes #225 
Closes #214 
Closes #207
Closes #250 
Note: for planned enhancement, I said we would wrap the text to make the calendar view display long names clearer. Looking for opinions on this, whether its okay or not.
=> Fix bugs in the Developer guide that surfaced from PE dry run

docs/DeveloperGuide.md, docs/UserGuide.md
=> Final UG changes
